### ISSUE TITLE
RN72 Support

### ISSUE THREAD

**Issue by rony-arnac** [sourcetoad/vision-camera-plugin-barcode-scanner#41]
deps:

```
"dependencies": {
    "@hookform/resolvers": "^3.1.0",
    "@react-native-async-storage/async-storage": "^1.19.2",
    "@react-native-clipboard/clipboard": "^1.11.1",
    "@react-navigation/native": "^6.1.1",
    "@react-navigation/native-stack": "^6.9.7",
    "@sourcetoad/vision-camera-plugin-barcode-scanner": "^1.0.1",
    "axios": "^1.4.0",
    "date-fns": "^2.30.0",
    "ethers": "5.7.2",
    "react": "18.2.0",
    "react-hook-form": "^7.44.3",
    "react-native": "0.72.1",
    "react-native-config": "^1.5.1",
    "react-native-get-random-values": "^1.9.0",
    "react-native-paper": "^5.8.0",
    "react-native-reanimated": "^3.4.2",
    "react-native-safe-area-context": "^4.4.1",
    "react-native-screens": "^3.18.2",
    "react-native-select-dropdown": "^3.3.4",
    "react-native-simple-dialogs": "^2.0.1",
    "react-native-vision-camera": "2.15.4",
    "text-encoding": "^0.7.0",
    "yup": "^1.2.0"
  },
```

followed example and it fails with

> ERROR  frame-processor/unavailable: Frame Processors are not enabled. See https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting, js engine: hermes

plz help!

thanks

**Comment by rony-arnac** [comment]
it's https://github.com/mrousavy/react-native-vision-camera/pull/1533 probably

**Comment by iBotPeaches** [comment]
Hmm. I'm guessing this is a tough situation.

reanimated V2 doesn't support RN72
vision camera V2 needs reanimated
vision camera V3 is still in development

Our RN72 upgrade is blocked and I imagine it's because of this.

**Comment by rony-arnac** [comment]
sheeesh

**Comment by iBotPeaches** [comment]
Yep confirmed and adjusted title. We cannot support RN72 yet until Vision camera does.

 * Vision Camera v2 looks pretty EOL at the moment as author focuses on v3.
 * However, a donation given with request of "releasing a v2 patch" did work, so perhaps that can be used to entice a RN72 fix, but I doubt it because....
   * Vision v2 needs Reanimated 2 to support RN72
   * Reanimated 2 is EOL for Reanimated v3
   * Vision v2 doesn't support Reanimated v3
   * Vision v3 doesn't use Reanimated

**Comment by iBotPeaches** [comment]
Okay we are unblocked on this now.

* v3 support on v2 - https://github.com/mrousavy/react-native-vision-camera/releases/tag/v2.16.1
* v3 is out - https://github.com/mrousavy/react-native-vision-camera/releases/tag/v3.2.0
